<?php
   require_once('../recursos/header.php');
?>      
<div class="parrafos">
    <p style="text-align: center;"><strong><span style="text-decoration: underline;">POLÍTICAS DE PRIVACIDAD DE DATOS PERSONALES</span></strong></p>
    <p>&nbsp;</p>
    <p><strong> CHALET BELGA POLLOS DE LECHE A LA BRAZA EIRL </strong>&nbsp;en adelante <strong>CHALET BELGA</strong>, con domicilio en Jr. Domingo Cueto N° 444, distrito de Lince, provincia y departamento de Lima, tiene como propósito principal informar a nuestros clientes que respetamos su derecho a la privacidad cuando usa nuestra página web y se comunica electrónicamente con nosotros. Por eso, como parte de nuestro compromiso para cumplir con sus expectativas hemos establecido una política de protección de la privacidad para los usuarios de nuestra página web.&nbsp;De acuerdo con las disposiciones contenidas en la Ley de Protección de Datos Personales – (Ley No. 29733) y sus normas complementarias y conexas.</p>
    <p>La Ley de Protección de Datos Personales, su Reglamento y las normas que las modifique o reemplacen (en lo sucesivo, Normativa de protección de datos personales) establece que para efectuar el tratamiento de los datos o información de una persona es necesario su consentimiento previo, informado, expreso e inequívoco. Por tal motivo, conforme a la referida ley, en el uso de medios electrónicos, <strong>CHALET BELGA</strong> considerará que usted ha brindado adecuadamente su consentimiento cuando usted disponga en “hacer clic”, “cliquear” o “pinchar”, “dar un toque”, “touch” o “pad” u otros similares cuando se le pregunte por su aceptación a los presentes términos aplicables al tratamiento de sus datos personales. La autorización para el tratamiento de sus datos personales resulta obligatoria para la ejecución de las actividades descritas en las páginas web de <strong>CHALET BELGA</strong> y aquellas señaladas en la presente Política, y en caso de negativa, ellas no se podrán realizar.</p>
    <p><strong>CHALET BELGA</strong>&nbsp;ha adoptado todas las medidas de seguridad de protección de los datos personales legalmente requeridos, garantizando la confidencialidad de los datos de carácter personal facilitados por los Usuarios y su tratamiento de acuerdo con la legislación vigente para evitar cualquier manipulación indebida, pérdida, destrucción o acceso no autorizado por parte de terceros a esta información empleando los medios adecuados para contrarrestarlos.</p>
    <p><strong>1.- LA INFORMACIÓN QUE RECOLECTAMOS A TRAVÉS DE NUESTROS SITIOS WEB</strong></p>
    <p>Solo recolectamos los datos personales que usted nos desee proporcionar o que son necesarios para brindarle y mejorar nuestros productos y servicios, y para los fines que se describen en el punto 3 de la presente Política y que usted acepta libremente. Nosotros recolectamos información personal directa como <strong>nombres, apellidos, número de D.N.I., pasaporte o carné de extranjería, razón social, número de R.U.C., domicilio, correo electrónico, número de teléfono y celular</strong>; la que esté expresamente indicada en nuestros sitios web y redes sociales a través de formularios electrónicos u otros formatos; todo en ello en estricto cumplimiento de la Ley de Protección de Datos Personales. Dicha información podrá ser almacenada en una base de datos de titularidad de <strong>CHALET BELGA</strong>.</p>
    <p><strong>2.- GUARDAMOS SU INFORMACIÓN DE MANERA SEGURA</strong></p>
    <p><strong>CHALET BELGA</strong>&nbsp;podrá obtener información sobre el Titular de los Datos Personales, por cualquier medio permitido por la Ley, incluyendo mas no limitándose a la obtención de manera personal o mediante plataformas electrónicas y/o páginas web. El Titular de los Datos Personales, mediante el ingreso de sus datos en la Página Web o su entrega de manera presencial, autoriza expresamente a <strong>CHALET BELGA</strong> y/o su personal administrativo autorizado a tratar la información facilitada de conformidad con las disposiciones de la Ley de Protección de Datos Personales – Ley No. 29733, su Reglamento, normas conexas y complementarias. <strong>CHALET BELGA</strong> procesará y protegerá los datos del Titular de los Datos Personales a través de medios digitales, técnicos y/o administrativos para garantizar un óptimo nivel de seguridad.</p>
    <p><strong>3.- FINALIDAD DEL TRATAMIENDO DE SUS DATOS PERSONALES</strong></p>
    <p>Podrá solicitar a los usuarios de esta página web (en adelante, los Titulares de los Datos Personales) datos personales con la siguiente finalidad:</p>
    <ul>
    <li>Procesar la compra realizada en virtud de la relación de consumo entablada con <strong>CHALET BELGA</strong>.</li>
    <li>Establecer un canal de comunicación con <strong>CHALET BELGA</strong> para informarle sobre el estado de su pedido u otra información relacionada a este.</li>
    <li>Incorporarlo en el historial de ventas de <strong>CHALET BELGA</strong> para fines estadísticos e históricos.</li>
    <li>Realización de encuestas de satisfacción respecto a los pedidos realizados y la atención brindada.</li>
    </ul>
    <p>Queda expresamente establecido que <strong>CHALET BELGA</strong> reconoce el derecho de los Titulares de los Datos Personales a manifestar su negativa respecto al uso y tratamiento de sus datos personales, cuando consideren que la información proporcionada no cumple ninguna de las funciones anteriormente descritas, o si los datos brindados no son necesarios para el establecimiento de una relación contractual. Esto sin perjuicio del derecho de revocación de consentimiento previamente otorgado por parte del Titular de los Datos Personales o bien para ejercer su derecho de oposición al uso de sus datos en términos de las disposiciones aplicables, derechos que en todo caso serán garantizados por la empresa en todo momento.</p>
    <p>Los Datos Personales proporcionados serán incorporados a la base de datos denominada <strong>“Clientes”</strong>, con inscripción ante el Registro Nacional de Protección de Datos Personales <strong>N° 18372</strong>; así mismo, podrán incorporarse, con las mismas finalidades, a otras bases de datos de Servicios del <strong>CHALET BELGA</strong> y/o de otras empresas subsidiarias, filiales, asociadas, afiliadas o miembros del grupo económico al cual ésta pertenece y/o terceros con los que éstas mantengan una relación contractual, las cuales se describen en el numeral 5 de la presente política.</p>
    <p><strong>4.- EJERCICIO DE SUS DERECHOS COMO TITULAR DE DATOS PERSONALES</strong></p>
    <p>El Titular de los Datos Personales es responsable de la exactitud, veracidad y autenticidad de los datos que proporcione. Los Titulares de los Datos Personales tendrán derecho de acceder a sus datos personales que hubieren sido recabados, efectuar correcciones a los mismos en caso&nbsp;de ser estos inexactos o incompletos, solicitar su eliminación cuando consideren que no son necesarios para alguna de las finalidades señaladas en la Política de Privacidad cuando esta sea legalmente procedente; y, a oponerse al uso o tratamiento de sus datos, en términos de la Ley y las disposiciones aplicables.</p>
    <p>El Titular de los Datos Personales puede ejercer sus derechos de <strong>acceso, información, rectificación, cancelación, oposición y revocación</strong> al uso de sus datos personales dirigiendo su solicitud con los requisitos solicitados en la Ley y demás normas aplicables a la siguiente dirección electrónica:&nbsp;<a href="mailto:servicioalcliente@chaletbelga.com">servicioalcliente@chaletbelga.com</a></p>
    <p>&nbsp;</p>
    <p><strong>5.- ACCESO Y TRANSFERENCIA</strong></p>
    <p><strong>CHALET BELGA</strong>&nbsp;no compartirá sus datos personales con terceros para una finalidad distinta a la que usted ha consentido. Sin embargo, también puede compartir, por encargo, sus datos personales en los siguientes casos:</p>
    <p><strong>Transferencia nacional de datos:&nbsp;</strong></p>
    <p>Los datos personales se transferirán a nivel nacional a las empresas pertenecientes al <strong>GRUPO EMPRESARIAL ROKY´S</strong>, las cuales son Inversiones Nor Chicken SAC, Inversiones House Chicken SAC, Inversiones Tomás Valle SAC, Inversiones Plaza San Martín SAC, Inversiones Comerciales Nazca SAC, Inversiones Kiyashi SA, Inversiones Turísticas Killa SAC, Inversiones Viena del Perú SAC, Inversiones Gran Chimú SAC e Inversiones Independencia SAC, las mismas que nos ayudan a mantener y administrar este u otros sitios (incluyendo pero no limitándose a las páginas web y cuentas que <strong>CHALET BELGA</strong> mantiene en redes sociales), y a realizar las actividades necesarias para el cumplimiento de las finalidades antes descritas para las que ha consentido el tratamiento de sus datos personales.</p>
    <p>Asimismo, también podemos facilitar sus datos personales a organismos de la Administración Pública y autoridades competentes si somos requeridos de hacerlo en virtud de obligaciones establecidas en ley. En algunos casos, debemos también proporcionar su información personal a las referidas entidades con objeto del desarrollo de un proceso legal, judicial y/o administrativo, conforme a ley.</p>
    <p><strong>Transferencia internacional de datos (Flujo transfronterizo):</strong></p>
    <p>El <strong>CHALET BELGA</strong> contrata los servicios en la nube (computación en la nuble) a través de <strong>AMAZON WEB SERVICES, INC.</strong>,&nbsp;la misma que posee el servidor donde pueden almacenar los datos personales ubicado en los Estados Unidos de América.</p>
    <p><strong>6.- PLAZO DE CONSERVACIÓN DE LOS DATOS PERSONALES:</strong></p>
    <p>Los datos personales proporcionados se conservarán mientras no se solicite su cancelación por el titular del dato.</p>
    <p><strong>7.- MODIFICACIONES A LA PRESENTE POLÍTICA DE PRIVACIDAD:</strong></p>
    <p>Con motivo de la mejora continua de nuestros procesos, <strong>CHALET BELGA</strong> podrá realizar modificaciones y correcciones a esta Política de Privacidad, a las cuales usted da conformidad. Por favor, verifique estos términos regularmente para consultar los cambios que puedan haber existido.</p>
</div>
<?php
    require_once('../recursos/footer.php')
?>